### ISSUE TITLE
Add Readme.md with proper description

### ISSUE THREAD

**Issue by soumikbaithalu** [soumik2012/Blog_Web_App-#1]

**Comment by codefunlearn** [comment]
Hi @soumik2012 I could do this (tech writer, front end student with basic HTML CSS Javascript). Could I have more information? Thanks

**Comment by soumikbaithalu** [comment]
> Hi @soumik2012 I could do this (tech writer, front end student with basic HTML CSS Javascript). Could I have more information? Thanks

Yes and more information about my project what it's content

**Comment by soumikbaithalu** [comment]
Also add emoji the information is contain on bullet point every one can read
